# Generated by Django 2.0.2 on 2018-02-28 17:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('icon', models.ImageField(upload_to='features/', verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('position', models.IntegerField(choices=[(0, 'wide'), (1, 'narrow')], verbose_name='Position')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight')),
            ],
            options={
                'ordering': ['weight', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('general_description', ckeditor.fields.RichTextField(verbose_name='General Description')),
                ('location_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Location Description')),
                ('interior_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Interior Description')),
                ('exterior_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Exterior Description')),
                ('lon', models.FloatField(verbose_name='Longitude')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('call2action', models.CharField(max_length=255, verbose_name='Call to Action')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('surface', models.IntegerField(blank=True, null=True, verbose_name='Surface')),
                ('bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Bedrooms')),
                ('bathrooms', models.IntegerField(blank=True, null=True, verbose_name='Bathrooms')),
                ('comment', ckeditor.fields.RichTextField(blank=True, verbose_name='Comment')),
                ('status', models.IntegerField(choices=[(0, 'archived'), (1, 'rented'), (2, 'sold'), (3, 'renting'), (4, 'in sale'), (5, 'future')], verbose_name='Status')),
                ('promoted', models.BooleanField(default=False, verbose_name='Promoted')),
                ('promote_weight', models.IntegerField(default=0, verbose_name='Promote Weight')),
                ('slider', models.BooleanField(default=False, verbose_name='Slider')),
                ('slider_weight', models.IntegerField(default=0, verbose_name='Slider Weight')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight')),
                ('categories', models.ManyToManyField(related_name='product_category', to='product.Category')),
                ('features', models.ManyToManyField(blank=True, related_name='product_feature', to='product.Feature')),
            ],
            options={
                'ordering': ['-date', 'weight', 'id'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Project'),
        ),
    ]
