# Generated by Django 2.0.2 on 2018-02-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lon',
            new_name='long',
        ),
    ]
