# Generated by Django 2.0.2 on 2018-03-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180301_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['weight', 'id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date', 'weight', 'id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
